### PR TITLE
fix: navigate to app settings after changing language

### LINKED ISSUE #485: Navigate to App Setting after language change
Currently when a user selects a new language, they are navigated back to the Map screen. Instead of navigating the user to the map screen, navigate them back one screen (App Settings)

## To Do
- [ ] Navigate user to app settings after selecting a language

### Notion Issue
https://www.notion.so/digidem/jump-from-language-selection-to-main-screen-083962fa0aea439e9032d8eaea043936

### PR DESCRIPTION
**Pull request by achou11**
Fixes #485 

---

Preview:

https://github.com/user-attachments/assets/5cec9f71-f616-477f-9d44-fb68b55d6231

### CODE REVIEW

File: src/frontend/App.tsx [hunk 1]
```diff
@@ -78,14 +77,12 @@ const App = () => {
   }, []);
 
   return (
-    <IntlProvider>
```
Comment (achou11) [inline src/frontend/App.tsx:81]: this is an extra intl provider that isn't needed (already set up in AppProviders)

File: src/frontend/contexts/IntlContext.tsx [hunk 2]
```diff
@@ -30,7 +30,6 @@ export const IntlProvider = ({children}: {children: React.ReactNode}) => {
 
   return (
     <IntlProviderOrig
-      key={appLocale}
```
Comment (achou11) [inline src/frontend/contexts/IntlContext.tsx:33]: this was causing essentially the whole app to remount when switching languages. a fun one to debug and eventually find 😄

**Review by ErikSin — APPROVED** [review]
Thanks for helping me figure this out
