### PR TITLE
fix: handle category-related changes after importing a config more elegantly

### LINKED ISSUE #686: Custom Config imported / App Crash
Have not manage to reproduce by Jen. Ximena reproduced on 2 different devices but can no longer reproduce

Details and videos - https://www.notion.so/digidem/Custom-Config-imported-App-Crash-148f4de78c1040e1aaf00f868313e749

### PR DESCRIPTION
**Pull request by achou11**
Fixes #686 
Towards #611

More closely emulates the behavior of Mapeo Mobile when it comes to displaying an observation that has an unknown/unmatched preset/category.

Also properly invalidates query caches for other kinds of data that are affected by the introduction of a new project config.

Note that this doesn't fully fix the issue described in #611 , as I believe the cause is out of the scope of this PR. See https://github.com/digidem/comapeo-core/issues/821#issuecomment-2344231495. It does however make some progress towards fixing it. Before, I don't think those icons would ever load. Now, they will eventually load (helps to navigate in and out of screens for now).

---

https://github.com/user-attachments/assets/8c3487e9-fe90-4943-ba51-b9726ff5304b

### CODE REVIEW

File: src/frontend/hooks/useObservationWithPreset.ts [hunk 1]
```diff
@@ -7,13 +7,5 @@ export const useObservationWithPreset = (observationId: string) => {
   const {data: presets} = usePresetsQuery();
   const preset = matchPreset(observation.tags, presets);
 
-  if (!observation) {
-    throw new Error('Observation does not exist');
-  }
-
-  if (!preset) {
-    throw new Error('Preset does not exist');
-  }
```
Comment (achou11) [inline src/frontend/hooks/useObservationWithPreset.ts:16]: for posterity, this is what caused the error seen in the issue

File: src/frontend/hooks/server/presets.ts [hunk 2]
```diff
@@ -36,26 +33,3 @@ export function usePresetsMutation() {
...
-      return await projectApi.$icons.getIconUrl(docId, {
-        mimeType: 'image/png',
-        size: size,
-        pixelDensity: 3,
-      });
-    },
-    retry: 2,
-    retryDelay: 2000,
-    staleTime: 60000,
-    placeholderData: keepPreviousData,
```
Comment (achou11) [inline src/frontend/hooks/server/presets.ts:59]: pretty sure specifying these is not helpful. opted to remove them entirely unless there's a notable issue that can be fixed by one of them being specified (query uses defaults for some of these if not specified)

File: src/frontend/hooks/useSelectFileAndImportConfig.ts [hunk 3]
```diff
@@ -24,7 +27,12 @@ export function useSelectFileAndImportConfig() {
       }
     },
     onSuccess: () => {
-      return queryClient.invalidateQueries({queryKey: [PROJECT_SETTINGS_KEY]});
+      return Promise.all([
+        queryClient.invalidateQueries({queryKey: [FIELDS_KEY]}),
+        queryClient.invalidateQueries({queryKey: [ICONS_KEY]}),
+        queryClient.invalidateQueries({queryKey: [PROJECT_SETTINGS_KEY]}),
+        queryClient.invalidateQueries({queryKey: [PRESETS_KEY]}),
+      ]);
```
Comment (achou11) [inline src/frontend/hooks/useSelectFileAndImportConfig.ts:35]: I _think_ it makes sense to have the mutation wait for all of these to resolve. the tradeoff is a slightly longer mutation time in the `active` state when importing a config

File: src/frontend/hooks/server/presets.ts (hunk 2 above)
Comment (ErikSin) [reply src/frontend/hooks/server/presets.ts:59]: I think we should keep the retry to 2 or even 1 (as a stop gap to the stale fastify port problem)

**Review by ErikSin — APPROVED** [review]

File: src/frontend/hooks/server/presets.ts (hunk 2 above)
Comment (achou11) [reply src/frontend/hooks/server/presets.ts:59]: React Query defaults to 3 based on the docs: https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

image

Can make it explicit if that's preferred though

Comment (ErikSin) [reply src/frontend/hooks/server/presets.ts:59]: I think we should make it less than 3 because we know what the problem is, and so failing faster would be better for the UI

Comment (achou11) [reply src/frontend/hooks/server/presets.ts:59]: unless I'm misunderstanding and you're suggesting that we should reduce the retry count (which I don't think is what you mean)

Comment (achou11) [reply src/frontend/hooks/server/presets.ts:59]: made it 3 explicitly via https://github.com/digidem/comapeo-mobile/pull/687/commits/0c36158e7df21c5a557143e53d53b9c95fe11079

Comment (ErikSin) [reply src/frontend/hooks/server/presets.ts:59]: That is what I am suggesting. Have tanstack query retry less times so that it throws an error faster. On each retry it remain in the pending state. That way the user doesn't see the loading spinner for so long and just shows the default icon when the fastify server is using a stale port

Comment (achou11) [reply src/frontend/hooks/server/presets.ts:59]: > I think we should make it less than 3 because we know what the problem is, and so failing faster would be better for the UI

Ah i see. I'll reduce to 2 in that case. i think it's still useful to have a couple of retries because the issue doesn't always happen (but that probably largely depends on the device and other factors). I'd be curious to see how prevalent it is in a release build vs development mode

Comment (achou11) [reply src/frontend/hooks/server/presets.ts:59]: > That way the user doesn't see the loading spinner for so long and just shows the default icon when the fastify server is using a stale port

Just to clarify, the issue not the stale port (at least in the context of this PR) but the server not being ready when resuming the app. Point understood though

Comment (achou11) [reply src/frontend/hooks/server/presets.ts:59]: reduced to 2 via 898be8912e40b14fdc9171231b30742d50f5f75a
