### PR TITLE
Fix/manual gps when no location service

### LINKED ISSUE #685: Location not shared/ Cant save manual GPS
**Problem:**

- Device not sharing their location with CoMapeo
- User tries to create an observation, CM reminds user to share location
- User declines
- User tries to create an observation
    - in GPS - display*s Searching*
- User can save the observation without the prompt of saving location manually

https://www.notion.so/digidem/Location-not-shared-Cant-save-manual-GPS-962afb0da23441ab9998ba8b2fab0ca7

### PR DESCRIPTION
**Pull request by ErikSin**
fixes: #685 

image

### CODE REVIEW

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 1]
```diff
@@ -169,12 +210,56 @@ export const ObservationCreate = ({
...
+        onPress: () => navigation.navigate('ManualGpsScreen'),
+        style: 'cancel',
+      },
+      {
+        text: formatMessage(m.keepWaiting),
+        onPress: () => {},
+      },
+    ];
+
+    if (!value) throw new Error('no observation saved in persisted state ');
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: Probably shouldn't throw an error here in the case that this does actually happen, as it will cause the app to crash. Would suggest a no-op via early return or gracefully surfacing an error of some sort for now.

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 2]
```diff
@@ -224,6 +309,10 @@ export const ObservationCreate = ({
   );
 };
 
+function isGpsAccurate(accuracy?: number): boolean {
+  return typeof accuracy === 'number' && accuracy < MINIMUM_ACCURACY;
+}
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: nit: don't think it's necessary to have a separate function for this right now

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 3]
```diff
@@ -169,12 +210,56 @@ export const ObservationCreate = ({
...
+
+    // If we don't have accuracy, allow save anyway (this is a remnant from mapeo: https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/screens/ObservationEdit/SaveButton.js#L125C3-L125C50)
+    if (accuracy && !isGpsAccurate(accuracy)) {
+      Alert.alert(
+        formatMessage(m.weakGpsTitle),
+        formatMessage(m.weakGpsDesc),
+        confirmationOptions,
+      );
+      return;
+    }
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: if the observation location is set manually, we don't want to surface these. should add a check for `value.metadata?.manualLocation` being not true in both of these.

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 4]
```diff
@@ -15,6 +15,7 @@ import {ErrorBottomSheet} from '../../sharedComponents/ErrorBottomSheet';
 import {NativeStackNavigationOptions} from '@react-navigation/native-stack';
 import {HeaderLeft} from './HeaderLeft';
 import {ActionsRow} from '../../sharedComponents/ActionRow';
+import {Alert, AlertButton} from 'react-native';
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: nit:

```suggestion
import {Alert, type AlertButton} from 'react-native';
```

**Review by achou11 — CHANGES_REQUESTED** [review]

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 3 above)
Comment (achou11) [reply src/frontend/screens/ObservationCreate/index.tsx]: ~Ah with the fix applied in 5aab158e01d7a7c9f1fad97c5c22da0b37c80e78 i think that the situation I wrote above doesn't happen anymore~.  EDIT: nvm, i wasn't able to reproduce the above situation even without that commit, so maybe I'm just misreading code at this point 😅  

Still think it might be worth having that check anyways for clarity though. The `liveLocation` variable is a little confusing to me at a glance otherwise

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 4 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/d3519214756fc2fbe99980e4ad1e4ca8fb6024f9

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 3 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/d3519214756fc2fbe99980e4ad1e4ca8fb6024f9

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 2 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/d3519214756fc2fbe99980e4ad1e4ca8fb6024f9

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 1 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/d3519214756fc2fbe99980e4ad1e4ca8fb6024f9

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 5]
```diff
@@ -169,12 +211,68 @@ export const ObservationCreate = ({
...
+        style: 'cancel',
+      },
+      {
+        text: formatMessage(m.keepWaiting),
+        onPress: () => {},
+      },
+    ];
+
+    if (!value) {
+      noop();
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: This is not necessary

```suggestion
      noop();
```

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 6]
```diff
@@ -169,12 +211,68 @@ export const ObservationCreate = ({
...
+      return;
+    }
+
+    // If the user has already inputted a manual location, do not check if location is accurate
+    if (value.metadata?.manualLocation) {
+      createObservation();
+    }
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: Need to add a return if you're doing this

```suggestion
    if (value.metadata?.manualLocation) {
      createObservation();
      return;
    }
```

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 7]
```diff
@@ -15,6 +15,8 @@ import {ErrorBottomSheet} from '../../sharedComponents/ErrorBottomSheet';
 import {NativeStackNavigationOptions} from '@react-navigation/native-stack';
 import {HeaderLeft} from './HeaderLeft';
 import {ActionsRow} from '../../sharedComponents/ActionRow';
+import {Alert, type AlertButton} from 'react-native';
+import noop from '../../lib/noop';
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: See other comment where this is used.

```suggestion
```

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 8]
```diff
@@ -169,12 +211,68 @@ export const ObservationCreate = ({
...
+        confirmationOptions,
+      );
+      return;
+    }
+
+    // If we don't have accuracy, allow save anyway (this is a remnant from mapeo: https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/screens/ObservationEdit/SaveButton.js#L125C3-L125C50)
+    if (
+      accuracy &&
+      typeof accuracy === 'number' &&
+      accuracy < MINIMUM_ACCURACY
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: This should be checking if the accuracy is too large (since accuracy is the numeric range of distance in this case)

```suggestion
      accuracy >= MINIMUM_ACCURACY
```

File: src/frontend/screens/ObservationCreate/index.tsx [hunk 9]
```diff
@@ -36,8 +38,48 @@ const m = defineMessages({
...
+    description: 'Button to manually enter GPS coordinates',
+  },
+  keepWaiting: {
+    id: 'screens.ObservationCreate.keepWaiting',
+    defaultMessage: 'Continue waiting',
+    description: 'Button to cancel save and continue waiting for GPS',
+  },
 });
 
+const MINIMUM_ACCURACY = 10;
```
Comment (achou11) [inline src/frontend/screens/ObservationCreate/index.tsx]: think this should be renamed to `MAXIMUM_ACCURACY` or something similar? See other comment where this is used, but this should be representing the maximum value we allow without asking the user about potentially inserting a manual one.

**Review by achou11 — CHANGES_REQUESTED** [review]

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 8 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: Im a little confused here. I think you are right, but historically we have used `accuracy < MINIMUM_ACCURACY` in comapeo mobile. Why has it worked before?

Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: see: https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/screens/ObservationEdit/SaveButton.js#L126

Comment (achou11) [reply src/frontend/screens/ObservationCreate/index.tsx]: Mapeo Mobile performs a different check. It's checking to see that the accuracy is valid and good enough (i.e. `accuracy < 10`) first and if it is, goes straight ahead to saving the draft.

https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/screens/ObservationEdit/SaveButton.js#L85-L95

https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/screens/ObservationEdit/SaveButton.js#L116-L127

Your PR is doing checking for cases where it's invalid or insufficient first, in order to potentially open the dialogs about manually setting a coordinate.

Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: RIght....I should probably just read the code 😬

Comment (achou11) [reply src/frontend/screens/ObservationCreate/index.tsx]: Yeah i think the `MINIMUM_ACCURACY` naming is a bit confusing since accuracy is one of those inverted quantities (in this case at least). Ideally it would be more descriptive in this context 😅

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 9 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/9ed6b36b9c35fd46ccb358820f0d0980cfc3aab7

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 8 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/9ed6b36b9c35fd46ccb358820f0d0980cfc3aab7

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 7 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/9ed6b36b9c35fd46ccb358820f0d0980cfc3aab7

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 6 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/9ed6b36b9c35fd46ccb358820f0d0980cfc3aab7

File: src/frontend/screens/ObservationCreate/index.tsx (hunk 5 above)
Comment (ErikSin) [reply src/frontend/screens/ObservationCreate/index.tsx]: https://github.com/digidem/comapeo-mobile/pull/702/commits/9ed6b36b9c35fd46ccb358820f0d0980cfc3aab7

**Comment by ErikSin** [comment]
Ok! i have tested it out on my device and it is doing what it should be doing: Asking for GPS when accuracy is greater than 10 and saving otherwise

**Review by achou11 — APPROVED** [review]
Might want to update this PR with develop first since there have been some changes introduced (although no merge conflicts it seems)

**Comment by achou11** [comment]
Also should update the PR title before merging!
