### PR TITLE
fix: Updates styling of how to join a project.

### LINKED ISSUE #948: (Correction) Add help icon
How to Join page is missing help icon and generally needs corrected fonts and spacing

https://www.notion.so/digidem/Correction-Add-help-icon-10b1b08162d58088bc73f7542521740d?pvs=4

### PR DESCRIPTION
**Pull request by cimigree**
closes #948 

- This PR adds a help icon and corrects the styling of the how to join a project screen.
- It uses the updated Header and Body Text with the color specified in the Figma
- It spaces it to reflect what is in the FIgma
- It updates the button to be what the outlined buttons throughout the app are [supposed to look like](https://www.notion.so/digidem/Correction-Correct-style-for-secondary-buttons-10b1b08162d5801eb19be0c1f6b1be80)
- [(but which we aren't doing just yet)](https://github.com/digidem/comapeo-mobile/issues/979)

- Here is the [FIGMA (sort of](https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=291-4476&t=jNP9tEeyOi3DuK9m-0))

- But [the Notion Doc](https://www.notion.so/digidem/Correction-Add-help-icon-10b1b08162d58088bc73f7542521740d) is more clear to me about what the changes needed to be because it includes the new button.
---

**Here is a screenshot from my pixel of what I did.**

<image src="https://github.com/user-attachments/assets/6abf43c7-22cc-46ac-9f8b-611a4d630555" width="350" />

### CODE REVIEW

File: src/frontend/screens/Settings/CreateOrJoinProject/JoinExistingProject.tsx [hunk 1]
```diff
@@ -27,34 +29,75 @@ export const JoinExistingProject = ({
...
+    color: NEW_DARK_GREY,
+  },
+  heading: {
     textAlign: 'center',
+    color: DARK_GREY,
+  },
+  instructions: {
+    textAlign: 'center',
+    color: DARK_GREY,
+    lineHeight: 24,
```
Comment (achou11) [inline src/frontend/screens/Settings/CreateOrJoinProject/JoinExistingProject.tsx:95]: out of curiosity: wonder if this line height should be shared by all usages of `BodyText`?

**Review by achou11 — APPROVED** [review]

File: src/frontend/screens/Settings/CreateOrJoinProject/JoinExistingProject.tsx (hunk 1 above)
Comment (cimigree) [reply src/frontend/screens/Settings/CreateOrJoinProject/JoinExistingProject.tsx:95]: I think that is probably a question for design...
