### PR TITLE
fix: Only allow coordinator to update config

### LINKED ISSUE #755: Only Coordinator can import Config
Coordinators, not participants, should be able to import a config

## To Do
- [ ] Disable participants from importing a config

### PR DESCRIPTION
**Pull request by ErikSin**
fixes #755 

### Participant Screen:
image

### Coordinator Screen:
image

### CODE REVIEW

**Review by achou11 — DISMISSED** [review]
I suggest creating a query that wraps `projectApi.$getOwnRole()`, which should make this PR more succinct.

also, would rename the PR to classify this as a fix instead of a chore

(also sorry for jumping in, didn't see the assigned reviewer until after reading through the code)

**Comment by cimigree** [comment]
I will wait until Andrew's requests are addressed before reviewing if that is ok, @ErikSin

**Comment by ErikSin** [comment]
@achou11 i have added your suggestions! Thanks

File: src/frontend/hooks/server/projects.ts [hunk 1]
```diff
@@ -147,3 +148,14 @@ export function useImportProjectConfig() {
     },
   });
 }
+
+export function useGetOwnRole() {
+  const {projectId, projectApi} = useActiveProject();
+
+  return useQuery({
+    queryKey: [OWN_ROLE, projectId],
```
Comment (ErikSin) [inline src/frontend/hooks/server/projects.ts]: `OWN_ROLE` is not fully necessary at this point, but in the future there could be the possibility of your role changing, hence why I created this query key

Comment (cimigree) [inline src/frontend/hooks/server/projects.ts]: Could you use a more descriptive key besides OWN_ROLE? USER_ROLE_KEY or something?

**Review by cimigree — APPROVED** [review]
One minor suggestion. I think it's good to have this query in place. I think we will use it again soon for determining editing capabilities on observations.

I tested it out on two devices running in development and it worked great.

**Comment by achou11** [comment]
@ErikSin another reminder to rename the PR to classify this as a fix, not a chore

File: src/frontend/hooks/server/projects.ts (hunk 1 above)
Comment (ErikSin) [reply src/frontend/hooks/server/projects.ts]: yeah, i think it would be good to distinguish between a user role query vs this devices role query. Maybe `THIS_USERS_ROLE_KEY`?
