### PR TITLE
fix: add back settings

### LINKED ISSUE #1131: New Menu / Add back Device Name
**Description**
https://www.notion.so/digidem/Add-back-Device-Name-1e31b08162d58068892dfb3275c54192
https://www.notion.so/digidem/Address-Device-Name-across-Multiple-Projects-1e31b08162d580fa9c25e243cd1279e1

Device Name was removed Project Settings, and now users do not have a way to edit their Device name. Also, with the introduction of Multi-project, editing the name device-wide is ideal, instead of project-wide.

**Todo**

- [ ] Add **Device Name** button to top of **Settings/App Settings** (top of Language)
- [ ] When editing the device name, this name should be edited across all projects

### LINKED ISSUE #1136: New Menu / Add back Remote Archive
https://www.notion.so/digidem/Add-back-Remote-Archive-1e61b08162d580c6a67fd1c871c399a3

**Todo**
Remote archive ON or OFF - Coordinator

Image

- [ ] Introduce the Remote Archive button as design
- [ ] When tapping on "View details" go to the existing screen

Remote archive ON  Participant
- [ ] Display the Remote Archive button as designed, set to ON
- [ ] Card isnt clickable

**Design**
https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/-Mobile--CoMapeo?node-id=4556-2052&t=iOW2jdEc1YPY67de-0

### LINKED ISSUE #1139: Add back Test Data
Add it back to App Settings

### PR DESCRIPTION
**Pull request by cimigree**
closes #1131
closes #1136 
closes #1139

### Changes
- Adds back the menu item to edit a device name and puts it in App Settings at the top
   - The issue asks that the device name be tied to multiple projects, but that is already the case so nothing needs to be changed for that.
- Adds back the menu item to create test data in settings
- Adds the card within the project menu to add a remote archive 
  - that card is there for any coordinator, even one on a solo project. Not sure if that is as it should be.

### Screenshots
<image src="https://github.com/user-attachments/assets/06994fe2-5043-488e-a3f4-9beaee09f644" width="250" />
<image src="https://github.com/user-attachments/assets/bbf67dc0-a397-4633-b8a2-d481996c6b39" width="250" />

### CODE REVIEW

**Review by achou11 — DISMISSED** [review]
Thanks for fixing!

**Comment by achou11** [comment]
> that card is there for any coordinator, even one on a solo project. Not sure if that is as it should be.

I _thought_ this would be fine but I ran into an error trying to add a remote server when on the solo project. my guess is that it's because the project doesn't have a name, but will confirm that in a moment. might need to hide that card in the case of the solo project.

File: src/frontend/screens/Settings/ProjectSettings/index.tsx [hunk 1]
```diff
@@ -106,13 +127,26 @@ export const ProjectSettings = () => {
...
+            icon={<ExchangeIcon width={24} height={24} />}
+            title={formatMessage(
+              remoteArchiveOn ? m.remoteArchiveOn : m.remoteArchiveOff,
+            )}
+            subtitle={formatMessage(m.remoteArchiveDesc)}
+            buttonText={formatMessage(m.viewDetails)}
+            onPress={() =>
+              navigate(remoteArchiveOn ? 'RemoteArchiveOn' : 'RemoteArchiveOff')
+            }
+          />
```
Comment (achou11) [inline src/frontend/screens/Settings/ProjectSettings/index.tsx]: > that card is there for any coordinator, even one on a solo project. Not sure if that is as it should be.

I _thought_ this would be fine but I ran into an error trying to add a remote server when on the solo project. my guess is that it's because the project doesn't have a name, but will confirm that in a moment. might need to hide that card in the case of the solo project.

**Review by achou11 — CHANGES_REQUESTED** [review]

File: src/frontend/screens/Settings/ProjectSettings/index.tsx (hunk 1 above)
Comment (achou11) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx]: yeah can confirm that once I named the project, adding the remote server worked. guess this needs to be conditionally rendered based on whether the current project has a name at least

**Comment by cimigree** [comment]
> * that card is there for any coordinator, even one on a solo project. Not sure if that is as it should be.

Yeah, @achou11  I was wondering about that.

File: src/frontend/screens/Settings/ProjectSettings/index.tsx (hunk 1 above)
Comment (achou11) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx]: alternatively, can update the remote archive screen to have some UI similar to the invite screen in the case where the project doesn't have a name yet i.e. prompting the user to set a project name. that probably requires more design work so i think conditionally rendering is sufficient for now.

Comment (cimigree) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx]: > alternatively, can update the remote archive screen to have some UI similar to the invite screen in the case where the project doesn't have a name yet i.e. prompting the user to set a project name

What do you think? Is there someone I should ask about that determination?

Comment (achou11) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx]: I think for now, conditionally rendering is sufficient since that's what was done in the past:

https://github.com/digidem/comapeo-mobile/pull/1100/files#diff-895678048c685b29813a9219ff1c3487e7f1ca70a230e3bc991a23522455a4e9L81

however, I think the check should be based on the project having a name, as opposed to the number of projects we have. I don't see any reason to disallow adding a remote archive on the solo project.

Comment (cimigree) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx]: > I don't see any reason to disallow adding a remote archive on the solo project.


Hmm. I find this confusing. The thing that determines if it is a "solo" project is if it has a name... not actually if there is anyone else on the project. So, yes the check I added is if it is A Solo Project (meaning it is unnamed and still has the default name as we have it -- "My Solo Project").

Comment (achou11) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx]: Yeah maybe my use of "solo" is too confusing. My main point is that you should be able to add a remote archive regardless of how many projects exist. As long as a project has a name, adding a remote archive should be allowed.

File: src/frontend/screens/Settings/ProjectSettings/index.tsx [hunk 2]
```diff
@@ -105,6 +126,19 @@ export const ProjectSettings = () => {
...
+          title={formatMessage(
+            remoteArchiveOn ? m.remoteArchiveOn : m.remoteArchiveOff,
+          )}
+          subtitle={formatMessage(m.remoteArchiveDesc)}
+          buttonText={formatMessage(m.viewDetails)}
+          onPress={() =>
+            navigate(remoteArchiveOn ? 'RemoteArchiveOn' : 'RemoteArchiveOff')
+          }
+        />
+      )}
```
Comment (achou11) [inline src/frontend/screens/Settings/ProjectSettings/index.tsx:141]: this doesn't properly guard against the issue i ran into. needs a check like `isCoordinator && projectInfo.name !== undefined`

**Review by achou11 — CHANGES_REQUESTED** [review]

File: src/frontend/screens/Settings/ProjectSettings/index.tsx (hunk 2 above)
Comment (achou11) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx:141]: unless the intention is to be okay with running into the error in that case? i'd be okay with that too but need some clarity on what the intended UX is

**Review by achou11 — APPROVED** [review]
decided that the issue i raised is non-blocking and kind of an edge case. just a little bit confusing when you do run into it but that can be addressed separately

File: src/frontend/screens/Settings/ProjectSettings/index.tsx (hunk 2 above)
Comment (achou11) [reply src/frontend/screens/Settings/ProjectSettings/index.tsx:141]: decided that this is non-blocking. being able to go through this flow and running into the error is fine, although a bit unclear since we don't surface the actual reason right now. can be addressed separately.

**Comment by cimigree** [comment]
> decided that the issue i raised is non-blocking and kind of an edge case. just a little bit confusing when you do run into it but that can be addressed separately

Did you look at `useProjectRoleandDetails` because I think your point about lack of name is accounted for in there. If it isn't, I think we need to take a look at the hook again.

**Comment by achou11** [comment]
> Did you look at `useProjectRoleandDetails` because I think your point about lack of name is accounted for in there. If it isn't, I think we need to take a look at the hook again.

~guess I wasn't familiar with this hook! i think it's tangential to the issue I'm raising though, since it (fortunately) doesn't try to use a default project name if it's missing (so `projectName` could still be `undefined`).~ EDIT: I see what you're referring to in that hook. The check you added in https://github.com/digidem/comapeo-mobile/pull/1154/commits/b51030f467b0e8ccb564c29f64e79f606084aec4 is narrowing based on discriminate union provided by that hook, such that the project name is defined. That's the part that wasn't apparent to me - apologies 😄

File: src/frontend/screens/Settings/ProjectSettings/index.tsx (hunk 2 above)
Comment (achou11) [inline src/frontend/screens/Settings/ProjectSettings/index.tsx:141]: Upon some additional thinking, one thing that isn't clear to me from a UX perspective is if this screen should only be able to be accessed by a coordinator.

My initial thought is that anyone should be able to view this screen, but the actions that can be taken within it should be restricted (that screen currently does that). If that's the desired UX, this conditional check here is misaligned with that.
