### PR TITLE
Fix: share button sometimes not working after first share

### LINKED ISSUE #834: Share button /Inconsistent
https://www.notion.so/digidem/Share-difficulty-again-11a1b08162d5806e94e9d39378870e2f

### PR DESCRIPTION
**Pull request by cimigree**
closes #834 

### Description

- I came across this when developing Audio
- The urls for the attachments only work once for converting into readable files.
- So, in the Share button, after the first Share was pressed, the network call for converting the url to a base64 image was failing and no amount of time waiting would fix that.
- This PR uses the getUrl query to fetch a new url for each attachment every time the share button is pressed because the hook can't be used in regular functions or conditionally.
- We can't set the base64 in state because technically opening the share menu is putting the app in the background and state would clear out when share is pressed (something else I came across in the Audio development)
- This is working well, so hoping it works for you too!
- I also added failOnCancel: false so there is no error thrown if a user decides not to share the observation

### To test

1. Create an observation or observations with attachments and some without
2. Share them as many times as you want without leaving the observation screen.
3. I can't test on What's App so please test on What's App for me

### CODE REVIEW

File: src/frontend/screens/Observation/Buttons.tsx [hunk 1]
```diff
@@ -8,16 +8,15 @@ import {useNavigationFromRoot} from '../../hooks/useNavigationWithTypes';
 import {useDeleteObservation} from '../../hooks/server/observations';
 import {Text} from '../../sharedComponents/Text';
```
Comment (ErikSin) [inline src/frontend/screens/Observation/Buttons.tsx]: can you replace this Text Element?

File: src/frontend/screens/Observation/Buttons.tsx [hunk 2]
```diff
@@ -117,36 +113,47 @@ export const ButtonFields = ({
     ]);
   }
 
-  async function handlePressShare() {
+  async function fetchFreshUrls() {
```
Comment (ErikSin) [inline src/frontend/screens/Observation/Buttons.tsx:117]: I think this can be simplified a bit. 2 main things. if you await`Promise.all`, it resolves (or rejects) all the promises inside the array. So it is redundant (and in certain edgecases lead to unwanted behaviour) to await all the objects inside the array. 

Secondly you can prefilter the array using the functions you created to determine if it is type audio or photo before you put them in the `promise.all`. That way you dont have to do a bunch of checks afterwards for null/undefined as well as type photo and audio

Here is what I would suggest

```ts

//defined outside the react component:
function isPhotoOrAudio(
  attachment: Attachment,
): attachment is Attachment & {type: 'photo' | 'audio'} {
  return isSavedPhoto(attachment) || isAudioAttachment(attachment);
}

// inside the react component:
async function fetchFreshUrls() {
    const {attachments} = observation;

    if (attachments.length === 0) {
      return [];
    }

    return await Promise.all(
      attachments.filter(isPhotoOrAudio).map(attachment => {
        return projectApi.$blobs.getUrl({
          driveId: attachment.driveDiscoveryId,
          name: attachment.name,
          type: attachment.type,
          variant: 'original',
        });
      }),
    );
  }

**Review by ErikSin — CHANGES_REQUESTED** [review]
just left a comment about simplifying the code

File: src/frontend/screens/Observation/Buttons.tsx (hunk 2 above)
Comment (cimigree) [reply src/frontend/screens/Observation/Buttons.tsx:117]: [9af300f](https://github.com/digidem/comapeo-mobile/pull/847/commits/9af300f79d54f28a85d7487d12fb983f71421c2f)

File: src/frontend/screens/Observation/Buttons.tsx (hunk 1 above)
Comment (cimigree) [reply src/frontend/screens/Observation/Buttons.tsx]: [9af300f](https://github.com/digidem/comapeo-mobile/pull/847/commits/9af300f79d54f28a85d7487d12fb983f71421c2f)

**Review by ErikSin — APPROVED** [review]
Seems to be working well! Thanks for doing that
